Repository hubblestack/hubble, pull requests merged in 2019-08, with the labels that each got.

#693 Fixing windows service management
  pkg/windows/build_pkg.ps1
  pkg/windows/create_build_env.ps1
  pkg/windows/dockerfile
  pkg/windows/hubble-Setup.nsi
  pkg/windows/hubble.conf
  pkg/windows/prerequisites.ps1
  pkg/windows/pyinstaller-requirements.txt
Labels: Packaging, Windows

#700 Adding support for debian 10 packages
  pkg/debian10/Dockerfile
  pkg/debian10/pyinstaller-requirements.txt
  pkg/dev/debian10/Dockerfile
  pkg/dev/debian10/pyinstaller-requirements.txt
Labels: Enhancement, Packaging

#702 defaults fix
  hubblestack/extmods/modules/conf_publisher.py
  hubblestack/extmods/returners/splunk_fdg_return.py
  hubblestack/extmods/returners/splunk_nebula_return.py
  hubblestack/extmods/returners/splunk_nova_return.py
  hubblestack/extmods/returners/splunk_osqueryd_return.py
  hubblestack/extmods/returners/splunk_pulsar_return.py
Labels: To Backport

#704 fix for cloud_details grain
  hubblestack/extmods/grains/cloud_details.py
Labels: To Backport

#705 from hubblestack.extmods.fdg.process import encode_base64 issues …
  hubblestack/extmods/fdg/process.py
  hubblestack/extmods/fdg/readfile.py
  hubblestack/utils/encoding.py
Labels: To Backport

#706 Adding single proxy override variable support
  .gitignore
  conf/hubble
  hubblestack/extmods/fileserver/azurefs.py
  hubblestack/hec/obj.py
Labels: Bug, To Backport

#714 variadic args fixes
  hubblestack/extmods/fdg/grep.py
  hubblestack/extmods/fdg/osquery.py
Labels: To Backport
